name: Playwright Tests
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.50.1
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Install Allure commandline
        run: |
          curl -o allure-2.24.1.tgz -OL https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.tgz
          tar -zxvf allure-2.24.1.tgz -C /opt/
          ln -s /opt/allure-2.24.1/bin/allure /usr/local/bin/allure

      - name: Start shopping store application
        run: |
          chmod +x ./shopping-store-linux-amd64
          ./shopping-store-linux-amd64 &
          echo "Waiting for application to start..."
          for i in {1..30}; do
            if curl -s http://localhost:2221 >/dev/null; then
              echo "Application started successfully!"
              exit 0
            fi
            sleep 1
          done
          echo "Application failed to start"
          exit 1

      - name: Run playwright tests
        run: npm run test:ci

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results -o allure-report --clean
          
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30